export const courses = [
  // ── BEGINNER COURSES (₹999 – ₹1,499) ──────────────────────────────────────
  {
    id: 1,
    title: 'HTML & CSS Fundamentals',
    description: 'Start your coding journey here. Learn to build beautiful, responsive websites from scratch using HTML5 and modern CSS3.',
    duration: '4 weeks',
    level: 'Beginner',
    price: 12,
    priceINR: 999,
    eligibility: 'No experience needed. Just a laptop and an internet connection.',
    image: '🎨',
    color: 'from-orange-500/20 to-yellow-500/20',
    borderColor: 'border-orange-500/30',
    skills: ['HTML5', 'CSS3', 'Flexbox', 'Grid', 'Responsive Design', 'Animations'],
    students: 5800,
    rating: 4.8,
    badge: 'Beginner Friendly',
    badgeColor: 'bg-orange-400/15 text-orange-400 border-orange-400/30',
  },
  {
    id: 2,
    title: 'JavaScript Basics',
    description: 'Learn the language of the web. Variables, functions, DOM manipulation, events — everything you need to make websites interactive.',
    duration: '5 weeks',
    level: 'Beginner',
    price: 12,
    priceINR: 999,
    eligibility: 'Basic HTML & CSS knowledge is enough. No prior programming needed.',
    image: '⚡',
    color: 'from-yellow-500/20 to-amber-500/20',
    borderColor: 'border-yellow-500/30',
    skills: ['JavaScript', 'DOM', 'Events', 'Functions', 'Arrays', 'Fetch API'],
    students: 6200,
    rating: 4.9,
    badge: 'Most Popular',
    badgeColor: 'bg-yellow-400/15 text-yellow-400 border-yellow-400/30',
  },
  {
    id: 3,
    title: 'Git & GitHub for Beginners',
    description: 'Master version control — the #1 skill every developer needs. Learn Git, GitHub, branching, pull requests and team workflows.',
    duration: '2 weeks',
    level: 'Beginner',
    price: 12,
    priceINR: 999,
    eligibility: 'No coding experience required. Suitable for anyone starting out.',
    image: '🌿',
    color: 'from-green-500/20 to-emerald-500/20',
    borderColor: 'border-green-500/30',
    skills: ['Git', 'GitHub', 'Branching', 'Pull Requests', 'Merge', 'Open Source'],
    students: 4900,
    rating: 4.8,
    badge: 'Essential Skill',
    badgeColor: 'bg-green-400/15 text-green-400 border-green-400/30',
  },
  {
    id: 4,
    title: 'Python for Beginners',
    description: 'Python is the easiest language to learn and the most in-demand. Build scripts, automate tasks, and lay the foundation for AI/ML.',
    duration: '5 weeks',
    level: 'Beginner',
    price: 15,
    priceINR: 1299,
    eligibility: 'Zero coding experience needed. Great for students and career-switchers.',
    image: '🐍',
    color: 'from-blue-500/20 to-indigo-500/20',
    borderColor: 'border-blue-500/30',
    skills: ['Python', 'Variables', 'Loops', 'Functions', 'File I/O', 'OOP Basics'],
    students: 7100,
    rating: 4.9,
    badge: 'Bestseller',
    badgeColor: 'bg-blue-400/15 text-blue-400 border-blue-400/30',
  },

  // ── INTERMEDIATE COURSES (₹1,499 – ₹1,999) ────────────────────────────────
  {
    id: 5,
    title: 'React.js Crash Course',
    description: 'Go from JavaScript to React in 6 weeks. Build modern UIs with components, hooks, state management and React Router.',
    duration: '6 weeks',
    level: 'Intermediate',
    price: 18,
    priceINR: 1499,
    eligibility: 'Must know HTML, CSS, and basic JavaScript (ES6+).',
    image: '⚛️',
    color: 'from-cyan-500/20 to-blue-500/20',
    borderColor: 'border-cyan-500/30',
    skills: ['React 18', 'Hooks', 'useState', 'useEffect', 'React Router', 'API Integration'],
    students: 4300,
    rating: 4.9,
    badge: 'Top Rated',
    badgeColor: 'bg-cyan-400/15 text-cyan-400 border-cyan-400/30',
  },
  {
    id: 6,
    title: 'Node.js & Express APIs',
    description: 'Build your first backend! Create REST APIs, handle authentication, connect to MongoDB and deploy your server to the cloud.',
    duration: '6 weeks',
    level: 'Intermediate',
    price: 18,
    priceINR: 1499,
    eligibility: 'JavaScript basics required (functions, async/await, promises).',
    image: '🔧',
    color: 'from-emerald-500/20 to-teal-500/20',
    borderColor: 'border-emerald-500/30',
    skills: ['Node.js', 'Express', 'REST APIs', 'MongoDB', 'JWT Auth', 'Deployment'],
    students: 3100,
    rating: 4.8,
    badge: null,
    badgeColor: '',
  },
  {
    id: 7,
    title: 'Tailwind CSS Mastery',
    description: 'Build stunning UIs 10x faster with Tailwind CSS. Modern utility-first styling, dark mode, animations and component design.',
    duration: '3 weeks',
    level: 'Intermediate',
    price: 15,
    priceINR: 1299,
    eligibility: 'Basic HTML and CSS knowledge required.',
    image: '💎',
    color: 'from-sky-500/20 to-cyan-500/20',
    borderColor: 'border-sky-500/30',
    skills: ['Tailwind CSS', 'Utility Classes', 'Dark Mode', 'Responsive', 'Animations', 'Components'],
    students: 2900,
    rating: 4.8,
    badge: 'New',
    badgeColor: 'bg-sky-400/15 text-sky-400 border-sky-400/30',
  },
  {
    id: 8,
    title: 'TypeScript for Developers',
    description: 'Level up your JavaScript with TypeScript. Types, interfaces, generics — write safer, more maintainable code for real-world projects.',
    duration: '4 weeks',
    level: 'Intermediate',
    price: 18,
    priceINR: 1499,
    eligibility: 'Solid JavaScript knowledge required (ES6+, classes, async/await).',
    image: '🔷',
    color: 'from-blue-500/20 to-violet-500/20',
    borderColor: 'border-blue-500/30',
    skills: ['TypeScript', 'Types', 'Interfaces', 'Generics', 'Decorators', 'tsconfig'],
    students: 2400,
    rating: 4.7,
    badge: 'In Demand',
    badgeColor: 'bg-violet-400/15 text-violet-400 border-violet-400/30',
  },
  {
    id: 9,
    title: 'SQL & Database Design',
    description: 'Master relational databases. Write powerful SQL queries, design schemas, optimize performance and work with PostgreSQL & MySQL.',
    duration: '4 weeks',
    level: 'Intermediate',
    price: 15,
    priceINR: 1299,
    eligibility: 'Basic programming knowledge helpful. No prior database experience needed.',
    image: '🗄️',
    color: 'from-amber-500/20 to-orange-500/20',
    borderColor: 'border-amber-500/30',
    skills: ['SQL', 'PostgreSQL', 'MySQL', 'Joins', 'Indexing', 'Schema Design', 'Transactions'],
    students: 2700,
    rating: 4.8,
    badge: null,
    badgeColor: '',
  },

  // ── ADVANCED / BUNDLED COURSES (₹1,999) ───────────────────────────────────
  {
    id: 10,
    title: 'MERN Stack Bootcamp',
    description: 'Build production-ready full-stack apps with MongoDB, Express, React, and Node.js. Ship real projects from day one.',
    duration: '16 weeks',
    level: 'Advanced',
    price: 24,
    priceINR: 1999,
    eligibility: 'Basic JavaScript & HTML knowledge required. Comfort with command line is a plus.',
    image: '🚀',
    color: 'from-violet-500/20 to-indigo-500/20',
    borderColor: 'border-violet-500/30',
    skills: ['React', 'Node.js', 'Express', 'MongoDB', 'REST APIs', 'JWT Auth', 'Deployment'],
    students: 2840,
    rating: 4.9,
    badge: 'Bestseller',
    badgeColor: 'bg-amber-400/15 text-amber-400 border-amber-400/30',
  },
  {
    id: 11,
    title: 'Full Stack Developer Path',
    description: 'The complete journey from zero to job-ready full stack engineer. Frontend, backend, databases, DevOps — everything covered.',
    duration: '24 weeks',
    level: 'Advanced',
    price: 24,
    priceINR: 1999,
    eligibility: 'No prior experience needed. Open to anyone willing to commit seriously.',
    image: '🏆',
    color: 'from-cyan-500/20 to-violet-500/20',
    borderColor: 'border-cyan-500/30',
    skills: ['HTML/CSS', 'JavaScript', 'React', 'Node.js', 'SQL', 'Docker', 'AWS'],
    students: 4120,
    rating: 4.8,
    badge: 'Most Popular',
    badgeColor: 'bg-cyan-400/15 text-cyan-400 border-cyan-400/30',
  },
  {
    id: 12,
    title: 'AI for Developers',
    description: 'Integrate AI/ML into your applications. Build with Python, TensorFlow, PyTorch and modern LLM APIs like OpenAI and LangChain.',
    duration: '12 weeks',
    level: 'Advanced',
    price: 24,
    priceINR: 1999,
    eligibility: 'Basic Python programming required. Some understanding of math/statistics is helpful.',
    image: '🤖',
    color: 'from-rose-500/20 to-orange-500/20',
    borderColor: 'border-rose-500/30',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'OpenAI API', 'LangChain', 'ML', 'Deep Learning'],
    students: 2210,
    rating: 4.9,
    badge: 'Trending',
    badgeColor: 'bg-rose-400/15 text-rose-400 border-rose-400/30',
  },
]

export const domains = [
  {
    id: 'frontend',
    icon: '🎨',
    title: 'Frontend Development',
    tagline: 'Build beautiful, interactive user interfaces',
    description: 'Frontend development is the craft of creating the visual and interactive elements that users directly experience. It combines design sensibility with technical precision to build fast, accessible, and delightful web applications.',
    color: 'from-blue-600 to-cyan-500',
    accentColor: 'text-cyan-400',
    borderColor: 'border-cyan-500/30',
    bgColor: 'from-cyan-500/10 to-blue-500/10',
    tools: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Next.js', 'Tailwind CSS', 'TypeScript', 'Vite'],
    careers: ['Frontend Engineer', 'UI Developer', 'React Developer', 'Web Designer'],
    projects: ['Portfolio site', 'E-commerce UI', 'Dashboard app', 'Animation showcase'],
    technologies: [
      { name: 'HTML', desc: 'Semantic structure and accessibility for the modern web' },
      { name: 'CSS', desc: 'Styling, animations, and responsive layouts with modern CSS' },
      { name: 'JavaScript', desc: 'Dynamic behavior and interactivity in the browser' },
      { name: 'React', desc: 'Component-based UI library for scalable applications' },
      { name: 'Next.js', desc: 'Production-grade React framework with SSR and routing' },
      { name: 'Tailwind CSS', desc: 'Utility-first CSS framework for rapid UI development' },
    ],
  },
  {
    id: 'backend',
    icon: '⚙️',
    title: 'Backend Development',
    tagline: 'Power applications with robust server logic',
    description: 'Backend engineering is the invisible engine that drives web applications. You design APIs, handle business logic, manage authentication, process data, and ensure your application scales to millions of users.',
    color: 'from-emerald-600 to-teal-500',
    accentColor: 'text-emerald-400',
    borderColor: 'border-emerald-500/30',
    bgColor: 'from-emerald-500/10 to-teal-500/10',
    tools: ['Node.js', 'Express.js', 'GraphQL', 'REST APIs', 'JWT', 'OAuth', 'Redis'],
    careers: ['Backend Engineer', 'API Developer', 'Node.js Developer', 'Systems Architect'],
    projects: ['REST API', 'Auth system', 'Real-time chat', 'Payment integration'],
    technologies: [
      { name: 'Node.js', desc: 'JavaScript runtime for scalable server-side applications' },
      { name: 'Express.js', desc: 'Minimal, flexible Node.js web application framework' },
      { name: 'REST APIs', desc: 'Industry-standard architectural style for web services' },
      { name: 'GraphQL', desc: 'Flexible query language for APIs with precise data fetching' },
      { name: 'Authentication', desc: 'JWT, OAuth, sessions — securing your applications' },
    ],
  },
  {
    id: 'database',
    icon: '🗄️',
    title: 'Database Engineering',
    tagline: 'Design systems that store and retrieve data brilliantly',
    description: 'Data is the foundation of every application. Database engineers design schemas, optimize queries, ensure data integrity, and build systems that handle millions of read/write operations per second.',
    color: 'from-amber-600 to-orange-500',
    accentColor: 'text-amber-400',
    borderColor: 'border-amber-500/30',
    bgColor: 'from-amber-500/10 to-orange-500/10',
    tools: ['MongoDB', 'PostgreSQL', 'Redis', 'Prisma', 'Mongoose', 'SQL', 'NoSQL'],
    careers: ['Database Administrator', 'Data Engineer', 'Backend Developer', 'DBA'],
    projects: ['Inventory system', 'Analytics DB', 'Social graph', 'Search engine'],
    technologies: [
      { name: 'MongoDB', desc: 'Flexible, document-oriented NoSQL database for modern apps' },
      { name: 'PostgreSQL', desc: 'Advanced relational database with powerful SQL features' },
      { name: 'Database Design', desc: 'Schema design, normalization, indexing, and optimization' },
    ],
  },
  {
    id: 'fullstack',
    icon: '🚀',
    title: 'Full Stack Development',
    tagline: 'End-to-end mastery across the entire web stack',
    description: 'Full stack developers architect and build complete web applications — from database schema to pixel-perfect UI. They are the most versatile engineers and command the highest demand in the job market.',
    color: 'from-violet-600 to-indigo-500',
    accentColor: 'text-violet-400',
    borderColor: 'border-violet-500/30',
    bgColor: 'from-violet-500/10 to-indigo-500/10',
    tools: ['MERN Stack', 'TypeScript', 'Docker', 'AWS', 'Vercel', 'Git', 'CI/CD'],
    careers: ['Full Stack Engineer', 'Startup CTO', 'Lead Developer', 'Tech Founder'],
    projects: ['SaaS platform', 'Social app', 'E-commerce site', 'Startup MVP'],
    technologies: [
      { name: 'MERN Stack', desc: 'MongoDB, Express, React, Node — the most popular full stack combination' },
      { name: 'Authentication Systems', desc: 'Complete auth flows: registration, login, JWT, OAuth, sessions' },
      { name: 'Deployment', desc: 'Ship to production with Vercel, Railway, AWS, and CI/CD pipelines' },
    ],
  },
  {
    id: 'devops',
    icon: '☁️',
    title: 'DevOps & Cloud',
    tagline: 'Ship faster, scale effortlessly, automate everything',
    description: 'DevOps engineers bridge development and operations. They build automated pipelines, containerize applications, manage cloud infrastructure, and ensure high availability for millions of users.',
    color: 'from-sky-600 to-blue-500',
    accentColor: 'text-sky-400',
    borderColor: 'border-sky-500/30',
    bgColor: 'from-sky-500/10 to-blue-500/10',
    tools: ['Docker', 'Kubernetes', 'AWS', 'GitHub Actions', 'Terraform', 'Nginx', 'Vercel'],
    careers: ['DevOps Engineer', 'Cloud Architect', 'SRE', 'Platform Engineer'],
    projects: ['CI/CD pipeline', 'K8s cluster', 'AWS deployment', 'Monitoring stack'],
    technologies: [
      { name: 'Docker', desc: 'Container platform for consistent, portable application deployment' },
      { name: 'CI/CD', desc: 'Automated testing and deployment pipelines with GitHub Actions' },
      { name: 'AWS', desc: 'Amazon Web Services — S3, EC2, Lambda, RDS and more' },
      { name: 'Vercel', desc: 'Zero-config deployment for frontend and serverless applications' },
      { name: 'Kubernetes', desc: 'Container orchestration for deploying and scaling applications' },
    ],
  },
  {
    id: 'web3',
    icon: '🔗',
    title: 'Web3 Development',
    tagline: 'Build the decentralized internet of tomorrow',
    description: 'Web3 developers build decentralized applications on blockchain networks. Smart contracts, DeFi protocols, NFT platforms, and DAOs — the frontier of software development.',
    color: 'from-pink-600 to-purple-500',
    accentColor: 'text-pink-400',
    borderColor: 'border-pink-500/30',
    bgColor: 'from-pink-500/10 to-purple-500/10',
    tools: ['Solidity', 'Ethereum', 'Hardhat', 'ethers.js', 'IPFS', 'Metamask', 'OpenZeppelin'],
    careers: ['Smart Contract Developer', 'DeFi Engineer', 'Blockchain Developer', 'Web3 Architect'],
    projects: ['Token contract', 'NFT marketplace', 'DeFi protocol', 'DAO governance'],
    technologies: [
      { name: 'Blockchain Basics', desc: 'Distributed ledgers, consensus mechanisms, cryptography' },
      { name: 'Smart Contracts', desc: 'Self-executing code on the blockchain — trustless automation' },
      { name: 'Solidity', desc: 'The primary programming language for Ethereum smart contracts' },
      { name: 'Ethereum', desc: 'The world computer — programmable blockchain for dApps' },
      { name: 'DeFi Apps', desc: 'Decentralized finance protocols — lending, DEXes, yield farming' },
    ],
  },
  {
    id: 'ai',
    icon: '🤖',
    title: 'Artificial Intelligence',
    tagline: 'Build intelligent systems that learn and adapt',
    description: 'AI/ML engineers build systems that can learn, reason, and make predictions. From image recognition to large language models — AI is transforming every industry and creating the most in-demand skills of the decade.',
    color: 'from-rose-600 to-red-500',
    accentColor: 'text-rose-400',
    borderColor: 'border-rose-500/30',
    bgColor: 'from-rose-500/10 to-red-500/10',
    tools: ['Python', 'TensorFlow', 'PyTorch', 'scikit-learn', 'OpenAI API', 'LangChain', 'NumPy'],
    careers: ['ML Engineer', 'AI Developer', 'Data Scientist', 'Research Engineer'],
    projects: ['Image classifier', 'Chatbot', 'Recommendation engine', 'LLM app'],
    technologies: [
      { name: 'Python', desc: 'The language of data science and machine learning' },
      { name: 'Machine Learning', desc: 'Supervised, unsupervised, and reinforcement learning algorithms' },
      { name: 'Deep Learning', desc: 'Neural networks, CNNs, RNNs, and transformers' },
      { name: 'TensorFlow', desc: "Google's production ML framework for training and deploying models" },
      { name: 'AI Applications', desc: 'Build real products with OpenAI, Anthropic, and open-source LLMs' },
    ],
  },
]

export const testimonials = [
  {
    name: 'Priya Sharma',
    role: 'Frontend Engineer @ Google',
    avatar: 'PS',
    color: 'from-violet-500 to-indigo-600',
    quote: 'CodeVerse completely changed my trajectory. I went from knowing basic HTML to landing my dream job at Google within 8 months. The curriculum is genuinely world-class.',
    course: 'Full Stack Developer',
    stars: 5,
  },
  {
    name: 'Marcus Chen',
    role: 'Backend Engineer @ Stripe',
    avatar: 'MC',
    color: 'from-cyan-500 to-blue-600',
    quote: 'The MERN Stack Bootcamp is the most comprehensive course I have ever taken. The projects are real-world, the mentors are incredible, and I felt job-ready by week 12.',
    course: 'MERN Stack Bootcamp',
    stars: 5,
  },
  {
    name: 'Aisha Patel',
    role: 'Full Stack Developer @ Vercel',
    avatar: 'AP',
    color: 'from-emerald-500 to-teal-600',
    quote: 'I was working at a call center. 6 months later I am at Vercel building the future of deployment. The community and mentorship here is something else entirely.',
    course: 'React Masterclass',
    stars: 5,
  },
  {
    name: 'James Okonkwo',
    role: 'Smart Contract Dev @ OpenSea',
    avatar: 'JO',
    color: 'from-pink-500 to-purple-600',
    quote: 'Web3 Development track is exceptional. Going deep on Solidity, DeFi, and smart contract security gave me skills that are genuinely rare and extremely well-compensated.',
    course: 'Web3 Development',
    stars: 5,
  },
  {
    name: 'Sofia Rodriguez',
    role: 'ML Engineer @ Meta',
    avatar: 'SR',
    color: 'from-rose-500 to-red-600',
    quote: 'The AI for Developers course gave me the exact skills Meta was looking for. The hands-on projects with real datasets made all the difference in interviews.',
    course: 'AI for Developers',
    stars: 5,
  },
  {
    name: 'Rahul Gupta',
    role: 'DevOps Engineer @ AWS',
    avatar: 'RG',
    color: 'from-amber-500 to-orange-600',
    quote: 'Transitioning from manual testing to DevOps seemed impossible. CodeVerse made it structured and achievable. Docker, Kubernetes, CI/CD — I mastered them all here.',
    course: 'Backend Engineering',
    stars: 5,
  },
]

export const stats = [
  { value: '50,000+', label: 'Students Enrolled', icon: '👨‍💻' },
  { value: '94%', label: 'Job Placement Rate', icon: '💼' },
  { value: '120+', label: 'Expert Instructors', icon: '🎓' },
  { value: '$95k', label: 'Avg Starting Salary', icon: '💰' },
]

export const instructors = [
  {
    name: 'Alex Rivera',
    role: 'Lead Instructor — Full Stack',
    company: 'Ex-Meta, Ex-Airbnb',
    avatar: 'AR',
    color: 'from-violet-500 to-indigo-600',
    specialties: ['React', 'Node.js', 'System Design'],
    bio: '12 years building at scale. Previously led frontend infra at Meta.',
    students: 8400,
  },
  {
    name: 'Dr. Yuki Tanaka',
    role: 'Lead Instructor — AI/ML',
    company: 'Ex-Google Brain',
    avatar: 'YT',
    color: 'from-rose-500 to-pink-600',
    specialties: ['TensorFlow', 'PyTorch', 'LLMs'],
    bio: 'PhD in Machine Learning. Published 20+ research papers at top conferences.',
    students: 5200,
  },
  {
    name: 'Omar Hassan',
    role: 'Lead Instructor — Web3',
    company: 'Ex-Ethereum Foundation',
    avatar: 'OH',
    color: 'from-amber-500 to-orange-600',
    specialties: ['Solidity', 'DeFi', 'Smart Contracts'],
    bio: 'Core contributor to 3 major DeFi protocols. Expert in smart contract security.',
    students: 3800,
  },
  {
    name: 'Priscilla Kwame',
    role: 'Lead Instructor — DevOps',
    company: 'Ex-AWS, Ex-Cloudflare',
    avatar: 'PK',
    color: 'from-sky-500 to-cyan-600',
    specialties: ['Kubernetes', 'AWS', 'CI/CD'],
    bio: 'Built and scaled cloud infrastructure for 50M+ user platforms.',
    students: 4100,
  },
]

export const pricingPlans = [
  {
    name: 'Starter',
    price: 12,
    priceINR: 999,
    period: '/course',
    description: 'Pick any single beginner course and start learning today',
    features: [
      'Access to 1 course',
      'Community forum access',
      '✅ Certificate of Completion',
      'Mobile app access',
      '1 live Q&A per month',
    ],
    cta: 'Start for ₹999',
    highlighted: false,
    badge: null,
  },
  {
    name: 'Pro',
    price: 18,
    priceINR: 1499,
    period: '/course',
    description: 'Best for intermediate learners ready to build real projects',
    features: [
      'Access to all intermediate courses',
      'Live mentorship sessions',
      'Career coaching',
      'Project code reviews',
      'Hiring network access',
      'Priority support',
      '🏅 Verified Certificate (LinkedIn-ready)',
      '📄 Letter of Recommendation (LOR)',
    ],
    cta: 'Start for ₹1,499',
    highlighted: true,
    badge: 'Most Popular',
  },
  {
    name: 'All Access',
    price: 24,
    priceINR: 1999,
    period: '/course',
    description: 'Full advanced bootcamps — MERN, Full Stack, AI & more',
    features: [
      'All 12 courses unlocked',
      'Live mentorship sessions',
      'Career coaching & mock interviews',
      'Project code reviews',
      'Hiring network access',
      '🏅 Verified Certificates for all courses',
      '📄 Letters of Recommendation',
      'Dedicated account manager',
    ],
    cta: 'Start for ₹1,999',
    highlighted: false,
    badge: null,
  },
]

export const faqs = [
  {
    q: 'Do I need prior coding experience?',
    a: 'Not at all! Our Full Stack Developer path starts from absolute zero. We have paths for complete beginners and for developers looking to level up. Check the "Eligibility" section on each course card for specific requirements.',
  },
  {
    q: 'Will I get a Certificate of Completion?',
    a: 'Yes! Every course comes with a verified Certificate of Completion upon finishing. Pro and Teams plan students also get LinkedIn-ready Verified Certificates recognized by 500+ hiring partners. You can request a Letter of Recommendation (LOR) from Subhadip after completing your course — great for job applications and higher studies.',
  },
  {
    q: 'How long until I am job-ready?',
    a: 'Most dedicated students land their first developer role within 6-12 months. Our 94% job placement rate speaks for itself — and our career team works with you until you get hired.',
  },
  {
    q: 'Are the courses self-paced or live?',
    a: 'Both! All courses include pre-recorded lessons you can watch anytime, plus weekly live sessions, office hours, and real-time Q&A with instructors.',
  },
  {
    q: 'What happens after I enroll?',
    a: 'You get instant access to your course materials, join our Discord community of 50,000+ developers, and are matched with a mentor. Your first live session is within 48 hours.',
  },
  {
    q: 'Do you offer a money-back guarantee?',
    a: 'Absolutely. We offer a 30-day no-questions-asked refund. We are that confident in the quality of our curriculum.',
  },
]
